VALID_PY = {
    "a",
    "ai",
    "an",
    "ang",
    "ao",
    "ba",
    "bai",
    "ban",
    "bang",
    "bao",
    "bei",
    "ben",
    "beng",
    "bi",
    "bian",
    "biang",
    "biao",
    "bie",
    "bin",
    "bing",
    "bo",
    "bu",
    "ca",
    "cai",
    "can",
    "cang",
    "cao",
    "ce",
    "cen",
    "ceng",
    "cha",
    "chai",
    "chan",
    "chang",
    "chao",
    "che",
    "chen",
    "cheng",
    "chi",
    "chong",
    "chou",
    "chu",
    "chua",
    "chuai",
    "chuan",
    "chuang",
    "chui",
    "chun",
    "chuo",
    "ci",
    "cong",
    "cou",
    "cu",
    "cuan",
    "cui",
    "cun",
    "cuo",
    "da",
    "dai",
    "dan",
    "dang",
    "dao",
    "de",
    "dei",
    "den",
    "deng",
    "di",
    "dia",
    "dian",
    "diao",
    "die",
    "ding",
    "diu",
    "dong",
    "dou",
    "du",
    "duan",
    "dui",
    "dun",
    "duo",
    "e",
    "ei",
    "en",
    "eng",
    "er",
    "fa",
    "fan",
    "fang",
    "fei",
    "fen",
    "feng",
    "fiao",
    "fo",
    "fou",
    "fu",
    "ga",
    "gai",
    "gan",
    "gang",
    "gao",
    "ge",
    "gei",
    "gen",
    "geng",
    "gong",
    "gou",
    "gu",
    "gua",
    "guai",
    "guan",
    "guang",
    "gui",
    "gun",
    "guo",
    "ha",
    "hai",
    "han",
    "hang",
    "hao",
    "he",
    "hei",
    "hen",
    "heng",
    "hong",
    "hou",
    "hu",
    "hua",
    "huai",
    "huan",
    "huang",
    "hui",
    "hun",
    "huo",
    "ji",
    "jia",
    "jian",
    "jiang",
    "jiao",
    "jie",
    "jin",
    "jing",
    "jiong",
    "jiu",
    "jv",
    "juan",
    "jue",
    "jun",
    "ka",
    "kai",
    "kan",
    "kang",
    "kao",
    "ke",
    "kei",
    "ken",
    "keng",
    "kong",
    "kou",
    "ku",
    "kua",
    "kuai",
    "kuan",
    "kuang",
    "kui",
    "kun",
    "kuo",
    "la",
    "lai",
    "lan",
    "lang",
    "lao",
    "le",
    "lei",
    "leng",
    "li",
    "lia",
    "lian",
    "liang",
    "liao",
    "lie",
    "lin",
    "ling",
    "liu",
    "lo",
    "long",
    "lou",
    "lu",
    "luan",
    "lun",
    "luo",
    "lv",
    "lve",
    "ma",
    "mai",
    "man",
    "mang",
    "mao",
    "me",
    "mei",
    "men",
    "meng",
    "mi",
    "mian",
    "miao",
    "mie",
    "min",
    "ming",
    "miu",
    "mo",
    "mou",
    "mu",
    "na",
    "nai",
    "nan",
    "nang",
    "nao",
    "ne",
    "nei",
    "nen",
    "neng",
    "ni",
    "nian",
    "niang",
    "niao",
    "nie",
    "nin",
    "ning",
    "niu",
    "nong",
    "nou",
    "nu",
    "nuan",
    "nuo",
    "nun",
    "nv",
    "nve",
    "o",
    "ou",
    "pa",
    "pai",
    "pan",
    "pang",
    "pao",
    "pei",
    "pen",
    "peng",
    "pi",
    "pian",
    "piao",
    "pie",
    "pin",
    "ping",
    "po",
    "pou",
    "pu",
    "qi",
    "qia",
    "qian",
    "qiang",
    "qiao",
    "qie",
    "qin",
    "qing",
    "qiong",
    "qiu",
    "qv",
    "quan",
    "que",
    "qun",
    "ran",
    "rang",
    "rao",
    "re",
    "ren",
    "reng",
    "ri",
    "rong",
    "rou",
    "ru",
    "rua",
    "ruan",
    "rui",
    "run",
    "ruo",
    "sa",
    "sai",
    "san",
    "sang",
    "sao",
    "se",
    "sen",
    "seng",
    "sha",
    "shai",
    "shan",
    "shang",
    "shao",
    "she",
    "shei",
    "shen",
    "sheng",
    "shi",
    "shou",
    "shu",
    "shua",
    "shuai",
    "shuan",
    "shuang",
    "shui",
    "shun",
    "shuo",
    "si",
    "song",
    "sou",
    "su",
    "suan",
    "sui",
    "sun",
    "suo",
    "ta",
    "tai",
    "tan",
    "tang",
    "tao",
    "te",
    "teng",
    "ti",
    "tian",
    "tiao",
    "tie",
    "ting",
    "tong",
    "tou",
    "tu",
    "tuan",
    "tui",
    "tun",
    "tuo",
    "wa",
    "wai",
    "wan",
    "wang",
    "wei",
    "wen",
    "weng",
    "wo",
    "wu",
    "xi",
    "xia",
    "xian",
    "xiang",
    "xiao",
    "xie",
    "xin",
    "xing",
    "xiong",
    "xiu",
    "xv",
    "xuan",
    "xue",
    "xun",
    "ya",
    "yan",
    "yang",
    "yao",
    "ye",
    "yi",
    "yin",
    "ying",
    "yo",
    "yong",
    "you",
    "yu",
    "yuan",
    "yue",
    "yun",
    "za",
    "zai",
    "zan",
    "zang",
    "zao",
    "ze",
    "zei",
    "zen",
    "zeng",
    "zha",
    "zhai",
    "zhan",
    "zhang",
    "zhao",
    "zhe",
    "zhei",
    "zhen",
    "zheng",
    "zhi",
    "zhong",
    "zhou",
    "zhu",
    "zhua",
    "zhuai",
    "zhuan",
    "zhuang",
    "zhui",
    "zhun",
    "zhuo",
    "zi",
    "zong",
    "zou",
    "zu",
    "zuan",
    "zui",
    "zun",
    "zuo",
}

JD_S2K = {
    "q": "q",
    "w": "w",
    "r": "r",
    "t": "t",
    "y": "y",
    "p": "p",
    "s": "s",
    "d": "d",
    "f": "f",
    "g": "g",
    "h": "h",
    "j": "j",
    "k": "k",
    "l": "l",
    "z": "z",
    "x": "x",
    "c": "c",
    "b": "b",
    "n": "n",
    "m": "m",
    "zh": ["q", "f"],
    "ch": ["w", "j"],
    "sh": "e",
    "": "x",
}

JD_Y2K = {
    "ua": "q",
    "iu": "q",
    "ei": "w",
    "un": "w",
    "e": "e",
    "eng": "r",
    "uan": "t",
    "ong": "y",
    "iong": "y",
    "ang": "p",
    "a": "s",
    "ia": "s",
    "ou": "d",
    "ie": "d",
    "an": "f",
    "uai": "g",
    "ing": "g",
    "ai": "h",
    "ue": "h",
    "u": "j",
    "er": "j",
    "i": "k",
    "uo": "l",
    "v": "l",
    "o": "l",
    "ao": "z",
    "iang": "x",
    "uang": "x",
    "iao": "c",
    "in": "b",
    "ui": "b",
    "en": "n",
    "ian": "m",
    "ve": "h",
}

JD_TO_PY =  {'wh': 'wai', 'bp': 'bang', 'nf': 'nan', 'dd': 'dou', 'lc': 'liao', 'sd': 'sou', 'wl': 'wo', 'ms': 'ma', 'lp': 'lang', 'fl': 'fo', 'cd': 'cou', 'xy': 'xiong', 'td': 'tie', 'hf': 'han', 'rq': 'rua', 'zh': 'zai', 'db': 'dui', 'lm': 'lian', 'sn': 'sen', 'fr': 'feng', 'nt': 'nuan', 'fg': 'zhuai', 'lz': 'lao', 'ny': 'nong', 'gg': 'guai', 'xw': 'xun', 'mf': 'man', 'tb': 'tui', 'yt': 'yuan', 'hd': 'hou', 'xk': 'xi', 'ej': 'shu', 'fj': 'fu', 'cf': 'can', 'yg': 'ying', 'xe': 'e', 'tk': 'ti', 'pc': 'piao', 'ty': 'tong', 'sy': 'song', 'sb': 'sui', 'zr': 'zeng', 'qz': 'zhao', 'rt': 'ruan', 'zf': 'zan', 'dh': 'dai', 'rr': 'reng', 'nd': 'nie', 'jd': 'chou', 'nr': 'neng', 'hh': 'hai', 'yp': 'yang', 'eg': 'shuai', 'jh': 'chai', 'dl': 'duo', 'ct': 'cuan', 'me': 'me', 'nh': 'nai', 'dz': 'dao', 'cj': 'cu', 'kb': 'kui', 'gj': 'gu', 'kp': 'kang', 'yl': 'yo', 'yh': 'yue', 'kx': 'kuang', 'jg': 'jing', 'cl': 'cuo', 'dj': 'du', 'bc': 'biao', 'nl': 'nv', 'yw': 'yun', 'hz': 'hao', 'sw': 'sun', 'ss': 'sa', 'hg': 'huai', 'wb': 'chui', 'cn': 'cen', 'sj': 'su', 'lf': 'lan', 'yb': 'yin', 'qm': 'qian', 'rp': 'rang', 'dn': 'den', 'tz': 'tao', 'bg': 'bing', 'cp': 'cang', 'tf': 'tan', 'tr': 'teng', 'jp': 'chang', 'ld': 'lou', 'mg': 'ming', 'pf': 'pan', 'mk': 'mi', 'jc': 'jiao', 'et': 'shuan', 'pn': 'pen', 'zw': 'zun', 'wx': 'chuang', 'gz': 'gao', 'fd': 'fou', 'kd': 'kou', 'ng': 'ning', 'fb': 'zhui', 'ws': 'wa', 'xj': 'er', 'he': 'he', 'dp': 'dang', 'ts': 'ta', 'gr': 'geng', 'pp': 'pang', 'dy': 'dong', 'el': 'shuo', 'bs': 'ba', 'zn': 'zen', 'bl': 'bo', 'df': 'dan', 'kt': 'kuan', 'ps': 'pa', 'xs': 'a', 'xh': 'ai', 'gy': 'gong', 'rz': 'rao', 'ly': 'long', 'lh': 'lve', 'xr': 'eng', 'hl': 'huo', 'kq': 'kua', 'qy': 'zhong', 'ph': 'pai', 'qg': 'qing', 'kg': 'kuai', 'll': 'luo', 'kf': 'kan', 'xz': 'ao', 'fp': 'fang', 'mm': 'mian', 'mq': 'miu', 'fw': 'zhun', 'ew': 'shun', 'xf': 'an', 'kz': 'kao', 'qf': 'zhan', 'xb': 'xin', 'qd': 'qie', 'bz': 'bao', 'br': 'beng', 'gx': 'guang', 'jn': 'chen', 'gq': 'gua', 'ky': 'kong', 'ft': 'zhuan', 'xn': 'n', 'kn': 'ken', 'kl': 'kuo', 'fq': 'zhua', 'ye': 'ye', 'dq': 'diu', 'js': 'jia', 'md': 'mie', 'gf': 'gan', 'ek': 'shi', 'mh': 'mai', 'nn': 'nen', 'pl': 'po', 'cy': 'cong', 'ef': 'shan', 'lk': 'li', 'ys': 'ya', 'wg': 'chuai', 'je': 'che', 'cb': 'cui', 'pz': 'pao', 'dg': 'ding', 'bh': 'bai', 'xl': 'xu', 'rk': 'ri', 'hp': 'hang', 'hw': 'hun', 'kr': 'keng', 'ds': 'da', 'er': 'sheng', 'ez': 'shao', 'lr': 'leng', 'kj': 'ku', 'pb': 'pin', 'jq': 'jiu', 'pj': 'pu', 'gn': 'gen', 'yd': 'you', 'le': 'le', 'nb': 'nin', 'qk': 'qi', 'jr': 'cheng', 'jy': 'chong', 'ke': 'ke', 'ne': 'ne', 'dm': 'dian', 'sk': 'si', 'cs': 'ca', 'pm': 'pian', 'qr': 'zheng', 'np': 'nang', 'ls': 'la', 'hq': 'hua', 'gs': 'ga', 'ml': 'mo', 'wk': 'chi', 'hx': 'huang', 'bw': 'bei', 'ck': 'ci', 'jm': 'jian', 'ns': 'na', 'dr': 'deng', 'wp': 'wang', 'gb': 'gui', 'nx': 'niang', 'kh': 'kai', 'bj': 'bu', 'rf': 'ran', 'zp': 'zang', 'dk': 'di', 'kw': 'kei', 'ex': 'shuang', 'fn': 'fen', 'zk': 'zi', 'ch': 'cai', 'jk': 'ji', 'se': 'se', 'wt': 'chuan', 'ff': 'fan', 'wj': 'chu', 'tl': 'tuo', 'hn': 'hen', 'fx': 'zhuang', 'cz': 'cao', 'fs': 'fa', 'nm': 'nian', 'wf': 'wan', 'dw': 'dun', 'pk': 'pi', 'ed': 'shou', 'tp': 'tang', 'wq': 'chua', 'th': 'tai', 'xq': 'xiu', 'fk': 'zhi', 'mj': 'mu', 'tw': 'tun', 'dt': 'duan', 'nz': 'nao', 'qx': 'qiang', 'mp': 'mang', 'xd': 'ou', 'jf': 'chan', 'es': 'sha', 'yk': 'yi', 'sh': 'sai', 'sp': 'sang', 'lw': 'lun', 'tc': 'tiao', 'lb': 'lin', 'qt': 'quan', 'hb': 'hui', 'gw': 'gun', 'te': 'te', 'yz': 'yao', 'cr': 'ceng', 'qh': 'que', 'hr': 'heng', 'de': 'de', 'ww': 'wei', 'en': 'shen', 'lg': 'ling', 'ht': 'huan', 'ze': 'ze', 'bd': 'bie', 'pg': 'ping', 'ee': 'she', 'yf': 'yan', 'sr': 'seng', 'gd': 'gou', 'rd': 'rou', 'zd': 'zou', 'tt': 'tuan', 'bf': 'ban', 'gp': 'gang', 'qw': 'zhei', 'xx': 'xiang', 'qp': 'zhang', 'hs': 'ha', 'gt': 'guan', 'xp': 'ang', 'lj': 'lu', 'wn': 'wen', 'jt': 'juan', 'xc': 'xiao', 'zz': 'zao', 'eq': 'shua', 'jw': 'jun', 'mb': 'min', 'mc': 'miao', 'ep': 'shang', 'mz': 'mao', 'jb': 'jin', 'jz': 'chao', 'dc': 'diao', 'bn': 'ben', 'pr': 'peng', 'nk': 'ni', 'sz': 'sao', 'qe': 'zhe', 'tg': 'ting', 'qs': 'zha', 'mr': 'meng', 'yj': 'yu', 'qb': 'qin', 'tm': 'tian', 'nc': 'niao', 'zb': 'zui', 'zy': 'zong', 'ry': 'rong', 'ql': 'qu', 'jl': 'ju', 'rj': 'ru', 'rl': 'ruo', 're': 're', 'pw': 'pei', 'yy': 'yong', 'fc': 'fiao', 'xt': 'xuan', 'qc': 'qiao', 'nj': 'nu', 'zj': 'zu', 'cw': 'cun', 'ge': 'ge', 'sl': 'suo', 'nw': 'nei', 'hy': 'hong', 'gl': 'guo', 'lq': 'liu', 'mw': 'mei', 'bk': 'bi', 'zs': 'za', 'hj': 'hu', 'lt': 'luan', 'xm': 'xian', 'bx': 'biang', 'bm': 'bian', 'st': 'suan', 'wr': 'weng', 'zl': 'zuo', 'rb': 'rui', 'lx': 'liang', 'jx': 'jiang', 'pd': 'pie', 'sf': 'san', 'ce': 'ce', 'gh': 'gai', 'xg': 'xing', 'mn': 'men', 'nq': 'niu', 'tj': 'tu', 'rw': 'run', 'eb': 'shui', 'eh': 'shai', 'rn': 'ren', 'ks': 'ka', 'zt': 'zuan', 'qn': 'zhen', 'bb': 'bin', 'qq': 'qiu'}
PY_TO_JD =  {'wai': 'wh', 'bang': 'bp', 'nan': 'nf', 'die': 'dd', 'liao': 'lc', 'sou': 'sd', 'chuo': 'wl', 'ma': 'ms', 'lang': 'lp', 'zhuo': 'fl', 'cou': 'cd', 'xiong': 'xy', 'tou': 'td', 'han': 'hf', 'rua': 'rq', 'zai': 'zh', 'dui': 'db', 'lian': 'lm', 'sen': 'sn', 'feng': 'fr', 'nuan': 'nt', 'zhuai': 'fg', 'lao': 'lz', 'nong': 'ny', 'guai': 'gg', 'ei': 'xw', 'man': 'mf', 'tui': 'tb', 'yuan': 'yt', 'hou': 'hd', 'xi': 'xk', 'shu': 'ej', 'zhu': 'fj', 'can': 'cf', 'ying': 'yg', 'e': 'xe', 'ti': 'tk', 'piao': 'pc', 'tong': 'ty', 'song': 'sy', 'sui': 'sb', 'zeng': 'zr', 'zhao': 'qz', 'ruan': 'rt', 'zan': 'zf', 'dai': 'dh', 'reng': 'rr', 'nou': 'nd', 'jie': 'jd', 'neng': 'nr', 'hai': 'hh', 'yang': 'yp', 'shuai': 'eg', 'jue': 'jh', 'duo': 'dl', 'cuan': 'ct', 'me': 'me', 'nve': 'nh', 'dao': 'dz', 'cu': 'cj', 'kui': 'kb', 'gu': 'gj', 'kang': 'kp', 'yo': 'yl', 'yue': 'yh', 'kuang': 'kx', 'jing': 'jg', 'cuo': 'cl', 'du': 'dj', 'biao': 'bc', 'nuo': 'nl', 'yun': 'yw', 'hao': 'hz', 'sun': 'sw', 'sa': 'ss', 'wo': 'wl', 'huai': 'hg', 'chui': 'wb', 'cen': 'cn', 'su': 'sj', 'lan': 'lf', 'yin': 'yb', 'qian': 'qm', 'rang': 'rp', 'den': 'dn', 'tao': 'tz', 'bing': 'bg', 'cang': 'cp', 'tan': 'tf', 'teng': 'tr', 'chang': 'jp', 'lie': 'ld', 'ming': 'mg', 'pan': 'pf', 'mi': 'mk', 'jiao': 'jc', 'shuan': 'et', 'pen': 'pn', 'zei': 'zw', 'chuang': 'wx', 'gao': 'gz', 'fou': 'fd', 'kou': 'kd', 'ning': 'ng', 'zhui': 'fb', 'chou': 'jd', 'wa': 'ws', 'er': 'xj', 'he': 'he', 'dang': 'dp', 'ta': 'ts', 'geng': 'gr', 'pang': 'pp', 'dong': 'dy', 'shuo': 'el', 'chai': 'jh', 'ba': 'bs', 'zen': 'zn', 'bo': 'bl', 'dan': 'df', 'kuan': 'kt', 'pa': 'ps', 'xia': 'xs', 'xue': 'xh', 'gong': 'gy', 'rao': 'rz', 'long': 'ly', 'lai': 'lh', 'eng': 'xr', 'huo': 'hl', 'kua': 'kq', 'qiong': 'qy', 'pai': 'ph', 'qing': 'qg', 'kuai': 'kg', 'lv': 'll', 'kan': 'kf', 'ao': 'xz', 'fang': 'fp', 'mian': 'mm', 'miu': 'mq', 'fei': 'fw', 'shei': 'ew', 'an': 'xf', 'lo': 'll', 'kao': 'kz', 'zhan': 'qf', 'xin': 'xb', 'zhou': 'qd', 'bao': 'bz', 'beng': 'br', 'guang': 'gx', 'chen': 'jn', 'gua': 'gq', 'kong': 'ky', 'ai': 'xh', 'zhuan': 'ft', 'en': 'xn', 'ken': 'kn', 'kuo': 'kl', 'zhua': 'fq', 'ye': 'ye', 'diu': 'dq', 'cha': 'js', 'mou': 'md', 'dou': 'dd', 'gan': 'gf', 'shi': 'ek', 'mai': 'mh', 'nen': 'nn', 'po': 'pl', 'jia': 'js', 'nai': 'nh', 'cong': 'cy', 'shan': 'ef', 'li': 'lk', 'ya': 'ys', 'chuai': 'wg', 'che': 'je', 'cui': 'cb', 'pao': 'pz', 'ding': 'dg', 'bai': 'bh', 'xv': 'xl', 'ri': 'rk', 'hang': 'hp', 'hei': 'hw', 'keng': 'kr', 'dia': 'ds', 'mie': 'md', 'sheng': 'er', 'zhun': 'fw', 'shao': 'ez', 'leng': 'lr', 'luo': 'll', 'ku': 'kj', 'pin': 'pb', 'jiu': 'jq', 'pu': 'pj', 'nv': 'nl', 'gen': 'gn', 'you': 'yd', 'le': 'le', 'nin': 'nb', 'qi': 'qk', 'cheng': 'jr', 'jiong': 'jy', 'ke': 'ke', 'ne': 'ne', 'dian': 'dm', 'si': 'sk', 'ca': 'cs', 'pian': 'pm', 'zheng': 'qr', 'nang': 'np', 'lia': 'ls', 'hua': 'hq', 'ga': 'gs', 'mo': 'ml', 'chi': 'wk', 'huang': 'hx', 'zhong': 'qy', 'bei': 'bw', 'ci': 'ck', 'jian': 'jm', 'na': 'ns', 'deng': 'dr', 'wang': 'wp', 'qie': 'qd', 'gui': 'gb', 'o': 'xl', 'niang': 'nx', 'kai': 'kh', 'bu': 'bj', 'ran': 'rf', 'zang': 'zp', 'di': 'dk', 'kun': 'kw', 'shuang': 'ex', 'fen': 'fn', 'zi': 'zk', 'cai': 'ch', 'ji': 'jk', 'se': 'se', 'chuan': 'wt', 'fan': 'ff', 'wu': 'wj', 'tuo': 'tl', 'hen': 'hn', 'zhuang': 'fx', 'cao': 'cz', 'fa': 'fs', 'nian': 'nm', 'wan': 'wf', 'dei': 'dw', 'pi': 'pk', 'shou': 'ed', 'tang': 'tp', 'chua': 'wq', 'tai': 'th', 'xiu': 'xq', 'zhi': 'fk', 'mu': 'mj', 'tun': 'tw', 'duan': 'dt', 'nao': 'nz', 'qiang': 'qx', 'mang': 'mp', 'xie': 'xd', 'fo': 'fl', 'chan': 'jf', 'sha': 'es', 'yi': 'yk', 'sai': 'sh', 'sang': 'sp', 'lei': 'lw', 'tiao': 'tc', 'lin': 'lb', 'dun': 'dw', 'quan': 'qt', 'hui': 'hb', 'gei': 'gw', 'te': 'te', 'yao': 'yz', 'ceng': 'cr', 'zhai': 'qh', 'heng': 'hr', 'de': 'de', 'chun': 'ww', 'shen': 'en', 'ling': 'lg', 'lve': 'lh', 'huan': 'ht', 'ze': 'ze', 'xun': 'xw', 'bie': 'bd', 'zun': 'zw', 'ping': 'pg', 'she': 'ee', 'yan': 'yf', 'seng': 'sr', 'gou': 'gd', 'rou': 'rd', 'zou': 'zd', 'gun': 'gw', 'fu': 'fj', 'tuan': 'tt', 'ban': 'bf', 'gang': 'gp', 'qun': 'qw', 'xiang': 'xx', 'zhang': 'qp', 'ha': 'hs', 'guan': 'gt', 'ang': 'xp', 'lu': 'lj', 'wei': 'ww', 'wen': 'wn', 'kei': 'kw', 'juan': 'jt', 'xiao': 'xc', 'zao': 'zz', 'shua': 'eq', 'jun': 'jw', 'min': 'mb', 'miao': 'mc', 'shang': 'ep', 'hun': 'hw', 'mao': 'mz', 'da': 'ds', 'ou': 'xd', 'jin': 'jb', 'shun': 'ew', 'chao': 'jz', 'diao': 'dc', 'ben': 'bn', 'tie': 'td', 'peng': 'pr', 'ni': 'nk', 'sao': 'sz', 'zhe': 'qe', 'ting': 'tg', 'qia': 'qs', 'a': 'xs', 'meng': 'mr', 'yu': 'yj', 'qin': 'qb', 'tian': 'tm', 'niao': 'nc', 'que': 'qh', 'zui': 'zb', 'chong': 'jy', 'zhei': 'qw', 'zong': 'zy', 'rong': 'ry', 'qv': 'ql', 'nie': 'nd', 'jv': 'jl', 'ru': 'rj', 'ruo': 'rl', 're': 're', 'pei': 'pw', 'la': 'ls', 'yong': 'yy', 'fiao': 'fc', 'xuan': 'xt', 'qiao': 'qc', 'nu': 'nj', 'zu': 'zj', 'cun': 'cw', 'ge': 'ge', 'suo': 'sl', 'nun': 'nw', 'hong': 'hy', 'chu': 'wj', 'guo': 'gl', 'liu': 'lq', 'mei': 'mw', 'nei': 'nw', 'bi': 'bk', 'za': 'zs', 'hu': 'hj', 'lou': 'ld', 'luan': 'lt', 'xian': 'xm', 'biang': 'bx', 'bian': 'bm', 'suan': 'st', 'lun': 'lw', 'weng': 'wr', 'zuo': 'zl', 'rui': 'rb', 'zha': 'qs', 'liang': 'lx', 'jiang': 'jx', 'pou': 'pd', 'san': 'sf', 'ce': 'ce', 'gai': 'gh', 'xing': 'xg', 'men': 'mn', 'niu': 'nq', 'tu': 'tj', 'run': 'rw', 'shui': 'eb', 'shai': 'eh', 'ren': 'rn', 'ka': 'ks', 'pie': 'pd', 'zuan': 'zt', 'zhen': 'qn', 'bin': 'bb', 'qiu': 'qq', 'n': 'xn', 'xu': 'xl', 'ju': 'jl', 'qu': 'ql'}

if __name__ == "__main__":
    PY_TO_JD = {}
    JD_TO_PY = {}
    for pinyin in VALID_PY:
        if pinyin[:2] in JD_S2K:
            sheng = pinyin[:2]
            yun = pinyin[2:]
        elif pinyin[0] in JD_S2K:
            sheng = pinyin[:1]
            yun = pinyin[1:]
        else:
            yun = pinyin
            sheng = ""
        s = ""
        if sheng == "zh":
            if yun[0] == "a" or yun[0] == "e" or yun[0] == "o":
                s = "q"
            else:
                s = "f"
        elif sheng == "ch":
            if yun[0] == "a" or yun[0] == "e" or yun[0] == "o":
                s = "j"
            else:
                s = "w"
        else:
            s = JD_S2K[sheng]

        y = JD_Y2K[yun]

        sy = s + y

        PY_TO_JD[pinyin] = sy
        JD_TO_PY[sy] = pinyin

    PY_TO_JD["n"] = "xn"
    JD_TO_PY["xn"] = "n"
    PY_TO_JD["xu"] = "xl"
    JD_TO_PY["xl"] = "xu"
    PY_TO_JD["ju"] = "jl"
    JD_TO_PY["jl"] = "ju"
    PY_TO_JD["qu"] = "ql"
    JD_TO_PY["ql"] = "qu"
    print("JD_TO_PY = ", JD_TO_PY)

    print("PY_TO_JD = ", PY_TO_JD)
