VALID_PY = {
    "a",
    "ai",
    "an",
    "ang",
    "ao",
    "ba",
    "bai",
    "ban",
    "bang",
    "bao",
    "bei",
    "ben",
    "beng",
    "bi",
    "bian",
    "biang",
    "biao",
    "bie",
    "bin",
    "bing",
    "bo",
    "bu",
    "ca",
    "cai",
    "can",
    "cang",
    "cao",
    "ce",
    "cen",
    "ceng",
    "cha",
    "chai",
    "chan",
    "chang",
    "chao",
    "che",
    "chen",
    "cheng",
    "chi",
    "chong",
    "chou",
    "chu",
    "chua",
    "chuai",
    "chuan",
    "chuang",
    "chui",
    "chun",
    "chuo",
    "ci",
    "cong",
    "cou",
    "cu",
    "cuan",
    "cui",
    "cun",
    "cuo",
    "da",
    "dai",
    "dan",
    "dang",
    "dao",
    "de",
    "dei",
    "den",
    "deng",
    "di",
    "dia",
    "dian",
    "diao",
    "die",
    "ding",
    "diu",
    "dong",
    "dou",
    "du",
    "duan",
    "dui",
    "dun",
    "duo",
    "e",
    "ei",
    "en",
    "eng",
    "er",
    "fa",
    "fan",
    "fang",
    "fei",
    "fen",
    "feng",
    "fiao",
    "fo",
    "fou",
    "fu",
    "ga",
    "gai",
    "gan",
    "gang",
    "gao",
    "ge",
    "gei",
    "gen",
    "geng",
    "gong",
    "gou",
    "gu",
    "gua",
    "guai",
    "guan",
    "guang",
    "gui",
    "gun",
    "guo",
    "ha",
    "hai",
    "han",
    "hang",
    "hao",
    "he",
    "hei",
    "hen",
    "heng",
    "hong",
    "hou",
    "hu",
    "hua",
    "huai",
    "huan",
    "huang",
    "hui",
    "hun",
    "huo",
    "ji",
    "jia",
    "jian",
    "jiang",
    "jiao",
    "jie",
    "jin",
    "jing",
    "jiong",
    "jiu",
    "ju",
    "juan",
    "jue",
    "jun",
    "ka",
    "kai",
    "kan",
    "kang",
    "kao",
    "ke",
    "kei",
    "ken",
    "keng",
    "kong",
    "kou",
    "ku",
    "kua",
    "kuai",
    "kuan",
    "kuang",
    "kui",
    "kun",
    "kuo",
    "la",
    "lai",
    "lan",
    "lang",
    "lao",
    "le",
    "lei",
    "leng",
    "li",
    "lia",
    "lian",
    "liang",
    "liao",
    "lie",
    "lin",
    "ling",
    "liu",
    "lo",
    "long",
    "lou",
    "lu",
    "luan",
    "lun",
    "luo",
    "lv",
    "lve",
    "ma",
    "mai",
    "man",
    "mang",
    "mao",
    "me",
    "mei",
    "men",
    "meng",
    "mi",
    "mian",
    "miao",
    "mie",
    "min",
    "ming",
    "miu",
    "mo",
    "mou",
    "mu",
    "na",
    "nai",
    "nan",
    "nang",
    "nao",
    "ne",
    "nei",
    "nen",
    "neng",
    "ni",
    "nian",
    "niang",
    "niao",
    "nie",
    "nin",
    "ning",
    "niu",
    "nong",
    "nou",
    "nu",
    "nuan",
    "nuo",
    "nun",
    "nv",
    "nue",
    "o",
    "ou",
    "pa",
    "pai",
    "pan",
    "pang",
    "pao",
    "pei",
    "pen",
    "peng",
    "pi",
    "pian",
    "piao",
    "pie",
    "pin",
    "ping",
    "po",
    "pou",
    "pu",
    "qi",
    "qia",
    "qian",
    "qiang",
    "qiao",
    "qie",
    "qin",
    "qing",
    "qiong",
    "qiu",
    "qu",
    "quan",
    "que",
    "qun",
    "ran",
    "rang",
    "rao",
    "re",
    "ren",
    "reng",
    "ri",
    "rong",
    "rou",
    "ru",
    "rua",
    "ruan",
    "rui",
    "run",
    "ruo",
    "sa",
    "sai",
    "san",
    "sang",
    "sao",
    "se",
    "sen",
    "seng",
    "sha",
    "shai",
    "shan",
    "shang",
    "shao",
    "she",
    "shei",
    "shen",
    "sheng",
    "shi",
    "shou",
    "shu",
    "shua",
    "shuai",
    "shuan",
    "shuang",
    "shui",
    "shun",
    "shuo",
    "si",
    "song",
    "sou",
    "su",
    "suan",
    "sui",
    "sun",
    "suo",
    "ta",
    "tai",
    "tan",
    "tang",
    "tao",
    "te",
    "teng",
    "ti",
    "tian",
    "tiao",
    "tie",
    "ting",
    "tong",
    "tou",
    "tu",
    "tuan",
    "tui",
    "tun",
    "tuo",
    "wa",
    "wai",
    "wan",
    "wang",
    "wei",
    "wen",
    "weng",
    "wo",
    "wu",
    "xi",
    "xia",
    "xian",
    "xiang",
    "xiao",
    "xie",
    "xin",
    "xing",
    "xiong",
    "xiu",
    "xu",
    "xuan",
    "xue",
    "xun",
    "ya",
    "yan",
    "yang",
    "yao",
    "ye",
    "yi",
    "yin",
    "ying",
    "yo",
    "yong",
    "you",
    "yu",
    "yuan",
    "yue",
    "yun",
    "za",
    "zai",
    "zan",
    "zang",
    "zao",
    "ze",
    "zei",
    "zen",
    "zeng",
    "zha",
    "zhai",
    "zhan",
    "zhang",
    "zhao",
    "zhe",
    "zhei",
    "zhen",
    "zheng",
    "zhi",
    "zhong",
    "zhou",
    "zhu",
    "zhua",
    "zhuai",
    "zhuan",
    "zhuang",
    "zhui",
    "zhun",
    "zhuo",
    "zi",
    "zong",
    "zou",
    "zu",
    "zuan",
    "zui",
    "zun",
    "zuo",
}

JD_S2K = {
    "q": "q",
    "w": "w",
    "r": "r",
    "t": "t",
    "y": "y",
    "p": "p",
    "s": "s",
    "d": "d",
    "f": "f",
    "g": "g",
    "h": "h",
    "j": "j",
    "k": "k",
    "l": "l",
    "z": "z",
    "x": "x",
    "c": "c",
    "b": "b",
    "n": "n",
    "m": "m",
    "zh": ["q", "f"],
    "ch": ["w", "j"],
    "sh": "e",
    "": "x",
}

JD_Y2K = {
    "ua": "q",
    "iu": "q",
    "ei": "w",
    "un": "w",
    "e": "e",
    "eng": "r",
    "uan": "t",
    "ong": "y",
    "iong": "y",
    "ang": "p",
    "a": "s",
    "ia": "s",
    "ou": "d",
    "ie": "d",
    "an": "f",
    "uai": "d",
    "ing": "d",
    "ai": "h",
    "ue": "h",
    "u": "j",
    "er": "j",
    "i": "k",
    "uo": "l",
    "v": "l",
    "o": "l",
    "ao": "z",
    "iang": "x",
    "uang": "x",
    "iao": "c",
    "in": "b",
    "ui": "b",
    "en": "k",
    "ian": "m",
}


JD_TO_PY = {
    "zl": "zuo",
    "kd": "kou",
    "cw": "cun",
    "bh": "bai",
    "bk": "bi",
    "gl": "guo",
    "ef": "shan",
    "bc": "biao",
    "he": "he",
    "rq": "rua",
    "ce": "ce",
    "mk": "men",
    "fc": "fiao",
    "lh": "lai",
    "ek": "shen",
    "lk": "li",
    "xw": "ei",
    "zj": "zu",
    "kr": "keng",
    "bf": "ban",
    "eb": "shui",
    "fb": "zhui",
    "mr": "meng",
    "cr": "ceng",
    "wl": "wo",
    "pp": "pang",
    "ed": "shuai",
    "yp": "yang",
    "re": "re",
    "hs": "ha",
    "gw": "gun",
    "dz": "dao",
    "jh": "chai",
    "qy": "qiong",
    "eh": "shai",
    "qt": "quan",
    "fw": "zhun",
    "rw": "run",
    "fd": "zhuai",
    "kz": "kao",
    "jx": "jiang",
    "rl": "ruo",
    "lw": "lei",
    "ww": "chun",
    "ex": "shuang",
    "dr": "deng",
    "fr": "feng",
    "nh": "nai",
    "qz": "zhao",
    "hb": "hui",
    "xj": "xu",
    "ky": "kong",
    "kj": "ku",
    "hh": "hai",
    "gx": "guang",
    "el": "shuo",
    "nf": "nan",
    "xz": "ao",
    "fj": "zhu",
    "qk": "qi",
    "gr": "geng",
    "fl": "fo",
    "ge": "ge",
    "xc": "xiao",
    "qs": "zha",
    "cs": "ca",
    "ds": "da",
    "qw": "qun",
    "sd": "sou",
    "tf": "tan",
    "tz": "tao",
    "nd": "nie",
    "lj": "lu",
    "ez": "shao",
    "gj": "gu",
    "xr": "eng",
    "yj": "yu",
    "jk": "ji",
    "ht": "huan",
    "lt": "luan",
    "pj": "pu",
    "rf": "ran",
    "xk": "en",
    "dh": "dai",
    "st": "suan",
    "nx": "niang",
    "rp": "rang",
    "zh": "zai",
    "ms": "ma",
    "ll": "lo",
    "rt": "ruan",
    "rb": "rui",
    "sl": "suo",
    "er": "sheng",
    "bd": "bie",
    "ls": "lia",
    "bm": "bian",
    "jt": "juan",
    "tk": "ti",
    "dd": "ding",
    "yh": "yue",
    "td": "ting",
    "hp": "hang",
    "hk": "hen",
    "nb": "nin",
    "qx": "qiang",
    "pk": "pi",
    "jd": "jing",
    "qp": "zhang",
    "ml": "mo",
    "hd": "huai",
    "qd": "zhou",
    "gd": "guai",
    "gf": "gan",
    "zd": "zou",
    "qm": "qian",
    "qf": "zhan",
    "dw": "dun",
    "pd": "pou",
    "kt": "kuan",
    "wb": "chui",
    "yy": "yong",
    "mf": "man",
    "nm": "nian",
    "qe": "zhe",
    "xt": "xuan",
    "ps": "pa",
    "sw": "sun",
    "tj": "tu",
    "eq": "shua",
    "cp": "cang",
    "nw": "nei",
    "yb": "yin",
    "cj": "cu",
    "qh": "que",
    "kw": "kei",
    "pm": "pian",
    "zk": "zi",
    "qb": "qin",
    "lq": "liu",
    "xy": "xiong",
    "ft": "zhuan",
    "rz": "rao",
    "wd": "chuai",
    "ze": "ze",
    "nr": "neng",
    "es": "sha",
    "pl": "po",
    "cz": "cao",
    "lb": "lin",
    "me": "me",
    "wr": "weng",
    "gt": "guan",
    "mp": "mang",
    "ne": "ne",
    "mw": "mei",
    "gs": "ga",
    "dq": "diu",
    "wp": "wang",
    "tm": "tian",
    "le": "le",
    "wk": "wen",
    "hx": "huang",
    "tt": "tuan",
    "ld": "lou",
    "xq": "xiu",
    "jm": "jian",
    "mm": "mian",
    "mc": "miao",
    "tc": "tiao",
    "bl": "bo",
    "md": "ming",
    "hz": "hao",
    "zt": "zuan",
    "ye": "ye",
    "tb": "tui",
    "df": "dan",
    "sk": "sen",
    "dl": "duo",
    "jf": "chan",
    "nt": "nuan",
    "ff": "fan",
    "mb": "min",
    "rj": "ru",
    "sy": "song",
    "et": "shuan",
    "zy": "zong",
    "db": "dui",
    "kp": "kang",
    "xs": "a",
    "rr": "reng",
    "ny": "nong",
    "xh": "ai",
    "xe": "e",
    "hw": "hei",
    "kq": "kua",
    "wj": "wu",
    "xd": "xie",
    "hl": "huo",
    "rk": "ri",
    "xb": "xin",
    "zb": "zui",
    "mz": "mao",
    "sj": "su",
    "lp": "lang",
    "nq": "niu",
    "jj": "ju",
    "wh": "wai",
    "gz": "gao",
    "xp": "ang",
    "wx": "chuang",
    "fk": "zhi",
    "sf": "san",
    "de": "de",
    "yf": "yan",
    "jb": "jin",
    "lz": "lao",
    "ss": "sa",
    "ws": "wa",
    "jy": "chong",
    "js": "jia",
    "ys": "ya",
    "hr": "heng",
    "zf": "zan",
    "fs": "fa",
    "gq": "gua",
    "mq": "miu",
    "sz": "sao",
    "tp": "tang",
    "dp": "dang",
    "se": "se",
    "kl": "kuo",
    "bz": "bao",
    "kk": "ken",
    "dk": "di",
    "cb": "cui",
    "gy": "gong",
    "wq": "chua",
    "yl": "yo",
    "gh": "gai",
    "bb": "bin",
    "nl": "nuo",
    "cd": "cou",
    "bp": "bang",
    "jw": "jun",
    "ry": "rong",
    "ck": "ci",
    "gp": "gang",
    "dj": "du",
    "pf": "pan",
    "bw": "bei",
    "rd": "rou",
    "zr": "zeng",
    "mj": "mu",
    "qr": "zheng",
    "fp": "fang",
    "qq": "qiu",
    "jr": "cheng",
    "pw": "pei",
    "nc": "niao",
    "dc": "diao",
    "te": "te",
    "qc": "qiao",
    "ch": "cai",
    "bj": "bu",
    "cy": "cong",
    "fx": "zhuang",
    "ts": "ta",
    "tr": "teng",
    "dm": "dian",
    "ph": "pai",
    "fq": "zhua",
    "zs": "za",
    "ks": "ka",
    "jc": "jiao",
    "tl": "tuo",
    "ep": "shang",
    "zp": "zang",
    "zw": "zei",
    "xx": "xiang",
    "hy": "hong",
    "ew": "shun",
    "zz": "zao",
    "xf": "an",
    "nz": "nao",
    "ns": "na",
    "jz": "chao",
    "lf": "lan",
    "ej": "shu",
    "pr": "peng",
    "wf": "wan",
    "kb": "kui",
    "br": "beng",
    "yd": "you",
    "th": "tai",
    "pb": "pin",
    "yw": "yun",
    "kf": "kan",
    "cf": "can",
    "gk": "gen",
    "nk": "nen",
    "np": "nang",
    "sr": "seng",
    "xm": "xian",
    "jp": "chang",
    "gb": "gui",
    "qj": "qu",
    "yt": "yuan",
    "tw": "tun",
    "kx": "kuang",
    "pc": "piao",
    "ct": "cuan",
    "dy": "dong",
    "lc": "liao",
    "mh": "mai",
    "xl": "o",
    "wt": "chuan",
    "je": "che",
    "pz": "pao",
    "hq": "hua",
    "ly": "long",
    "sb": "sui",
    "lm": "lian",
    "ty": "tong",
    "ee": "she",
    "hj": "hu",
    "kh": "kai",
    "sp": "sang",
    "hf": "han",
    "nj": "nu",
    "yk": "yi",
    "dt": "duan",
    "lx": "liang",
    "lr": "leng",
    "cl": "cuo",
    "sh": "sai",
    "bs": "ba",
    "jq": "jiu",
    "bx": "biang",
    "ke": "ke",
    "yz": "yao",
}
PY_TO_JD = {
    "zuo": "zl",
    "kuai": "kd",
    "cun": "cw",
    "bai": "bh",
    "ben": "bk",
    "guo": "gl",
    "shan": "ef",
    "biao": "bc",
    "he": "he",
    "rua": "rq",
    "ce": "ce",
    "mi": "mk",
    "fiao": "fc",
    "lve": "lh",
    "shi": "ek",
    "li": "lk",
    "xun": "xw",
    "zu": "zj",
    "keng": "kr",
    "ban": "bf",
    "shui": "eb",
    "zhui": "fb",
    "meng": "mr",
    "ceng": "cr",
    "chuo": "wl",
    "pang": "pp",
    "shou": "ed",
    "yang": "yp",
    "re": "re",
    "ha": "hs",
    "gei": "gw",
    "dao": "dz",
    "jue": "jh",
    "zhong": "qy",
    "shai": "eh",
    "quan": "qt",
    "fei": "fw",
    "run": "rw",
    "fou": "fd",
    "kao": "kz",
    "jiang": "jx",
    "ruo": "rl",
    "shen": "ek",
    "lun": "lw",
    "wei": "ww",
    "shuang": "ex",
    "deng": "dr",
    "feng": "fr",
    "nve": "nh",
    "zhao": "qz",
    "hui": "hb",
    "er": "xj",
    "kong": "ky",
    "ku": "kj",
    "hai": "hh",
    "guang": "gx",
    "shuo": "el",
    "nan": "nf",
    "ao": "xz",
    "fu": "fj",
    "zhen": "qk",
    "geng": "gr",
    "zhuo": "fl",
    "ge": "ge",
    "xiao": "xc",
    "qia": "qs",
    "ca": "cs",
    "dia": "ds",
    "zhei": "qw",
    "sou": "sd",
    "tan": "tf",
    "tao": "tz",
    "nou": "nd",
    "lu": "lj",
    "shao": "ez",
    "chun": "ww",
    "gu": "gj",
    "eng": "xr",
    "yu": "yj",
    "chen": "jk",
    "bi": "bk",
    "huan": "ht",
    "luan": "lt",
    "pu": "pj",
    "ran": "rf",
    "xi": "xk",
    "dai": "dh",
    "suan": "st",
    "niang": "nx",
    "rang": "rp",
    "zai": "zh",
    "ma": "ms",
    "lv": "ll",
    "ruan": "rt",
    "rui": "rb",
    "suo": "sl",
    "sheng": "er",
    "bing": "bd",
    "shuai": "ed",
    "la": "ls",
    "gun": "gw",
    "bian": "bm",
    "juan": "jt",
    "ti": "tk",
    "die": "dd",
    "luo": "ll",
    "yue": "yh",
    "tou": "td",
    "hang": "hp",
    "hen": "hk",
    "nin": "nb",
    "da": "ds",
    "qiang": "qx",
    "pen": "pk",
    "jie": "jd",
    "zhang": "qp",
    "mo": "ml",
    "hou": "hd",
    "qing": "qd",
    "gou": "gd",
    "gan": "gf",
    "zou": "zd",
    "qian": "qm",
    "zhan": "qf",
    "dei": "dw",
    "men": "mk",
    "kou": "kd",
    "pie": "pd",
    "kuan": "kt",
    "chui": "wb",
    "lo": "ll",
    "zhun": "fw",
    "yong": "yy",
    "man": "mf",
    "nian": "nm",
    "zhe": "qe",
    "xuan": "xt",
    "pa": "ps",
    "sun": "sw",
    "tu": "tj",
    "dou": "dd",
    "shua": "eq",
    "cang": "cp",
    "nun": "nw",
    "yin": "yb",
    "cu": "cj",
    "zhai": "qh",
    "kun": "kw",
    "pian": "pm",
    "zen": "zk",
    "qin": "qb",
    "liu": "lq",
    "xiong": "xy",
    "zhuan": "ft",
    "nei": "nw",
    "rao": "rz",
    "qiong": "qy",
    "chuai": "wd",
    "lia": "ls",
    "ze": "ze",
    "neng": "nr",
    "sha": "es",
    "po": "pl",
    "cao": "cz",
    "lin": "lb",
    "fo": "fl",
    "me": "me",
    "weng": "wr",
    "guan": "gt",
    "mang": "mp",
    "ne": "ne",
    "mei": "mw",
    "ga": "gs",
    "diu": "dq",
    "wang": "wp",
    "tian": "tm",
    "le": "le",
    "ei": "xw",
    "chi": "wk",
    "huang": "hx",
    "tuan": "tt",
    "lie": "ld",
    "xiu": "xq",
    "jian": "jm",
    "mian": "mm",
    "miao": "mc",
    "tiao": "tc",
    "bo": "bl",
    "chai": "jh",
    "mie": "md",
    "hao": "hz",
    "zuan": "zt",
    "ye": "ye",
    "tui": "tb",
    "dan": "df",
    "si": "sk",
    "duo": "dl",
    "chan": "jf",
    "nuan": "nt",
    "fan": "ff",
    "ling": "ld",
    "min": "mb",
    "ru": "rj",
    "song": "sy",
    "huai": "hd",
    "shuan": "et",
    "lai": "lh",
    "zong": "zy",
    "dui": "db",
    "zha": "qs",
    "kang": "kp",
    "xia": "xs",
    "reng": "rr",
    "qie": "qd",
    "xu": "xj",
    "nong": "ny",
    "xue": "xh",
    "en": "xk",
    "ding": "dd",
    "e": "xe",
    "hun": "hw",
    "kua": "kq",
    "chu": "wj",
    "zi": "zk",
    "ou": "xd",
    "huo": "hl",
    "ren": "rk",
    "ji": "jk",
    "xin": "xb",
    "zui": "zb",
    "mao": "mz",
    "qi": "qk",
    "su": "sj",
    "lang": "lp",
    "niu": "nq",
    "mou": "md",
    "ju": "jj",
    "pi": "pk",
    "wai": "wh",
    "gao": "gz",
    "ang": "xp",
    "chuang": "wx",
    "fen": "fk",
    "san": "sf",
    "de": "de",
    "yan": "yf",
    "jin": "jb",
    "lao": "lz",
    "zhuai": "fd",
    "sa": "ss",
    "wa": "ws",
    "jiong": "jy",
    "cha": "js",
    "ya": "ys",
    "heng": "hr",
    "chou": "jd",
    "zan": "zf",
    "fa": "fs",
    "gua": "gq",
    "miu": "mq",
    "sao": "sz",
    "tang": "tp",
    "ming": "md",
    "dang": "dp",
    "se": "se",
    "kuo": "kl",
    "bao": "bz",
    "ken": "kk",
    "den": "dk",
    "cui": "cb",
    "gong": "gy",
    "chua": "wq",
    "yo": "yl",
    "gai": "gh",
    "bin": "bb",
    "nv": "nl",
    "cou": "cd",
    "ri": "rk",
    "bang": "bp",
    "jun": "jw",
    "tie": "td",
    "rong": "ry",
    "cen": "ck",
    "gang": "gp",
    "ning": "nd",
    "du": "dj",
    "pan": "pf",
    "bei": "bw",
    "rou": "rd",
    "ai": "xh",
    "zeng": "zr",
    "mu": "mj",
    "zheng": "qr",
    "ping": "pd",
    "fang": "fp",
    "qiu": "qq",
    "cheng": "jr",
    "pei": "pw",
    "niao": "nc",
    "diao": "dc",
    "te": "te",
    "qiao": "qc",
    "cai": "ch",
    "bu": "bj",
    "lei": "lw",
    "lou": "ld",
    "cong": "cy",
    "chong": "jy",
    "dun": "dw",
    "zhuang": "fx",
    "ta": "ts",
    "teng": "tr",
    "xing": "xd",
    "nie": "nd",
    "dian": "dm",
    "pai": "ph",
    "zhua": "fq",
    "zhi": "fk",
    "di": "dk",
    "za": "zs",
    "ka": "ks",
    "jiao": "jc",
    "tuo": "tl",
    "shang": "ep",
    "hei": "hw",
    "zang": "zp",
    "zun": "zw",
    "xiang": "xx",
    "wu": "wj",
    "hong": "hy",
    "shei": "ew",
    "wen": "wk",
    "zao": "zz",
    "guai": "gd",
    "jia": "js",
    "zei": "zw",
    "an": "xf",
    "ting": "td",
    "nao": "nz",
    "na": "ns",
    "zhu": "fj",
    "qun": "qw",
    "chao": "jz",
    "lan": "lf",
    "shu": "ej",
    "peng": "pr",
    "bie": "bd",
    "wan": "wf",
    "kui": "kb",
    "beng": "br",
    "ying": "yd",
    "tai": "th",
    "pin": "pb",
    "you": "yd",
    "yun": "yw",
    "kan": "kf",
    "can": "cf",
    "gen": "gk",
    "ni": "nk",
    "nuo": "nl",
    "kei": "kw",
    "nang": "np",
    "que": "qh",
    "pou": "pd",
    "seng": "sr",
    "xian": "xm",
    "chang": "jp",
    "gui": "gb",
    "qu": "qj",
    "yuan": "yt",
    "nai": "nh",
    "sen": "sk",
    "tun": "tw",
    "jing": "jd",
    "kuang": "kx",
    "ci": "ck",
    "piao": "pc",
    "cuan": "ct",
    "dong": "dy",
    "liao": "lc",
    "mai": "mh",
    "o": "xl",
    "chuan": "wt",
    "che": "je",
    "pao": "pz",
    "wo": "wl",
    "hua": "hq",
    "nen": "nk",
    "long": "ly",
    "sui": "sb",
    "a": "xs",
    "lian": "lm",
    "tong": "ty",
    "she": "ee",
    "hu": "hj",
    "xie": "xd",
    "kai": "kh",
    "zhou": "qd",
    "sang": "sp",
    "han": "hf",
    "nu": "nj",
    "yi": "yk",
    "duan": "dt",
    "liang": "lx",
    "shun": "ew",
    "leng": "lr",
    "cuo": "cl",
    "sai": "sh",
    "ba": "bs",
    "jiu": "jq",
    "biang": "bx",
    "ke": "ke",
    "yao": "yz",
}

if __name__ == "__main__":
    PY_TO_JD = {}
    JD_TO_PY = {}
    for pinyin in VALID_PY:
        if pinyin[:2] in JD_S2K:
            sheng = pinyin[:2]
            yun = pinyin[2:]
        elif pinyin[0] in JD_S2K:
            sheng = pinyin[:1]
            yun = pinyin[1:]
        else:
            yun = pinyin
            sheng = ""
        s = ""
        if sheng == "zh":
            if yun[0] == "a" or yun[0] == "e" or yun[0] == "o":
                s = "q"
            else:
                s = "f"
        elif sheng == "ch":
            if yun[0] == "a" or yun[0] == "e" or yun[0] == "o":
                s = "j"
            else:
                s = "w"
        else:
            s = JD_S2K[sheng]

        y = JD_Y2K[yun]

        sy = s + y

        PY_TO_JD[pinyin] = sy
        JD_TO_PY[sy] = pinyin
    print(JD_TO_PY)

    print(PY_TO_JD)
